; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "KernelPanik - KlownWave"
#define MyAppPublisher "BitNet01"
#define MyAppURL "https://www.bitnet01.xyz"
;#define MyAppExeName "AS29 Studio.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{64A92997-FDDE-46BC-BFC0-6EFEE7DE62AA}
AppName={#MyAppName}
AppVersion=1.0
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\installer
OutputBaseFilename=KernelPanik - Klownwave - Windows
SetupIconFile=C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KKicon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
;Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked


[Dirs]
Name: "{app}\"; Permissions: everyone-full users-full
Name: "{app}\GUI"; Permissions: everyone-full users-full
Name: "{app}\UDOs"; Permissions: everyone-full users-full
Name: "{app}\Waves"; Permissions: everyone-full users-full

[Files]
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KlownWave\GUI\*"; DestDir: "{app}\GUI\"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: everyone-full users-full
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KlownWave\UDOs\*"; DestDir: "{app}\UDOs\"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: everyone-full users-full
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KlownWave\Waves\*"; DestDir: "{app}\Waves\"; Flags: ignoreversion recursesubdirs createallsubdirs; Permissions: everyone-full users-full
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KlownWave\KlownWave.csd"; DestDir: "{app}"; Flags: ignoreversion; Permissions: everyone-full users-full
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KlownWave\KlownWave.dll"; DestDir: "{app}"; Flags: ignoreversion; Permissions: everyone-full users-full
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\KlownWave\KlownWave.snaps"; DestDir: "{app}"; Flags: onlyifdoesntexist; Permissions: everyone-full users-full
Source: "C:\Users\franc\Downloads\KernelPanik - KlownWave - Windows\Csound6-windows_x86_64-6.16.0.exe"; DestDir: "{app}"; Flags: ignoreversion; Permissions: everyone-full users-full

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: "{app}\Csound6-windows_x86_64-6.16.0.exe"; Description: "Installing CSound is necessary to run KlownWave!"; Flags: waituntilterminated skipifsilent

